gg:
  jte:
    development-mode: false
    use-precompiled-templates: true

hawaii:
  rainfall:
    administrator:
      username: ${RAINGAUGE_ADMIN_USERNAME}
      password: ${RAINGAUGE_ADMIN_PASSWORD}

server:
  forward-headers-strategy: framework
