name: KAMAL Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: "KAMAL command to run"
        default: "kamal app details"
jobs:
  Command:
    runs-on: ubuntu-latest
    env:
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_ADMIN_USERNAME: ${{ secrets.KAMAL_ADMIN_USERNAME }}
      KAMAL_ADMIN_PASSWORD: ${{ secrets.KAMAL_ADMIN_PASSWORD }}
      KAMAL_PROXY_HOST: ${{ vars.KAMAL_PROXY_HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
      - name: Install dependencies
        run: |
          gem install kamal -v 2.12.0
      - name: Run KAMAL command
        run: ${{ github.event.inputs.command }}
